#!/bin/bash

if [[ -L $0 ]]; then
    DOTFILE_DIR="`readlink -e $0 | xargs dirname`"
else
    DOTFILE_DIR="`dirname $0`"
fi

fpath=($DOTFILE_DIR/lib $fpath)
for f in $DOTFILE_DIR/shell_startup/*; do
    source $f
done

# vim:filetype=sh
